apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress2
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:551940803425:certificate/e32b784b-294b-41ce-aef7-79908159b0a7
    alb.ingress.kubernetes.io/lister-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - host: appc.carlosnascimento.tk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appc-service
                port:
                  number: 80
    - host: appd.carlosnascimento.tk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: appd-service
                port:
                  number: 80