apiVersion: apps/v1
kind: Deployment
metadata:
  name: appd-deployment
  labels:
    app: appd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appd
  template:
    metadata:
      labels:
        app: appd
    spec:
      containers:
      - name: appd
        image: danurky/appd:v1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appd-service-nodeport
spec:
  type: NodePort
  selector:
    app: appd
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30304