apiVersion: apps/v1
kind: Deployment
metadata:
  name: appb-deployment
  labels:
    app: appb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appb
  template:
    metadata:
      labels:
        app: appb
    spec:
      containers:
      - name: appb
        image: danurky/appb:v1.0.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appb-service-nodeport
spec:
  type: NodePort
  selector:
    app: appb
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30302